apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4bl1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-4bl1@sha256:5b0c398a74d1eae65da6f09cf82321e01734fd64903c7b3f73ecbde74af86694
        name: my-nodejs
        resources: {}
status: {}
